# Boron

hide_ascii      = false
spacing         = 2
padding         = 0
separator       = ""
key_color       = "Blue"
separator_color = "Yellow"

[bar]
glyph           = "o"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = false

[box]
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[custom_ascii]
color           = "Yellow"
path            = "~/.config/macchina/logos/nixos.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = ""
kernel          = "󰹢"
battery         = "Battery"
os              = "OS"
de              = "󱂬"
wm              = "WM"
distro          = "󰌽"
terminal        = ""
shell           = ""
packages        = ""
uptime          = "Uptime"
memory          = "Memory"
machine         = ""
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "󰒓"
gpu             = "GPU"
disk_space      = "Disk Space"
